config/routes.rb
require 'api_constraints'

NcesLookup::Application.routes.draw do
  root to: 'home#index'
  get 'search' => 'home#search'
  resources :schools

  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get 'search', to: 'schools#search'
      resources :schools
    end
  end
end

app/models/school.rb
class School
  include Mongoid::Document

  after_validation :geocode

  field :nces_school_id
  field :state_school_id
  field :nces_district_id
  field :nces_state_district_id
  field :low_grade
  field :high_grade
  field :name
  field :district
  field :county
  field :street
  field :city
  field :state
  field :zip, type: Integer
  field :zipfour, type: Integer
  field :phone
  field :locale_code, type: Integer
  field :locale
  field :charter, type: Boolean
  field :magnet, type: Boolean
  field :students, type: Integer
  field :teachers, type: BigDecimal
  field :st_ratio, type: Float
  field :free_lunch, type: Integer
  field :reduced_lunch, type: Integer
  field :coordinates, type: Array

  include Geocoder::Model::Mongoid
  geocoded_by :address

  VALID_SEARCH_PARAMS = [
    :nces_school_id,
    :state_school_id,
    :low_grade,
    :high_grade,
    :name,
    :district,
    :county,
    :city,
    :state,
    :zip,
    :phone
  ].freeze

  def address
    "#{street} #{city}, #{state} #{zip} US" # US ONLY
  end

  def self.generate_search_params(params)
    if params[:query] && params[:query].is_number? && params[:query].length == 5
      # params[:zip] = 
      # params.delete(:query)
      return { zip: params[:query].to_i  }
    end

    valid_params = {}
    # VALID_SEARCH_PARAMS.each do |p|
    #   valid_params[p.to_sym] = /.*#{params[:query].upcase}.*/
    # end

    # valid_params = params.keys.collect(&:to_sym) & VALID_SEARCH_PARAMS
    # query_params = {}
    # valid_params.each { |p| query_params[p.to_sym] = params[p] }
    # [TODO] update method for string search on name from matching against only uppercase
    valid_params[:name] = /.*#{params[:query].upcase}.*/ if params[:query]
    # query_params
    valid_params
  end
end

app/controllers/api/v1/schools_controller.rb
class Api::V1::SchoolsController < ApplicationController
  before_filter :allow_cross_origin

  def index
    @schools = School.limit(20)
    render json: @schools
  end

  def search
    @schools = School.any_of(School.generate_search_params(params))
    render json: @schools
  end

  def allow_cross_origin
    response.headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :default_request_city

  def default_request_city
    
    query = Geocoder::Query.new("#{request.latitude}, #{request.longitude}")
    @request_location = query.execute.first
  rescue
    @request_city = 'Washington, DC'
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    Geocoder.configure(
      lookup: :bing,
      api_key: ENV['BING_API_KEY'],
      use_https: true,
      timeout: 30
    )
    begin
      @schools ||= School.near(@request_location).limit(10)
    rescue
      @schools = []
    end
  end

  def search
    skewl_params = School.generate_search_params(params)
    puts skewl_params
    @schools = School.any_of(skewl_params).limit(20)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def show
    @school = School.find(params[:id])
  end
end

app/helpers/api/v1/schools_helper.rb
module Api::V1::SchoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def booleanize(str)
    
    if str.downcase.include? 'y'
      true
    else
      false
    end
  rescue
    nil
    
  end
end

class String
  def is_number?
    
    true if Float(self)
  rescue
    false
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/_school.html.slim
= link_to(school.name, school_path(school))

app/views/home/index.html.slim
.row
  .main-search
    = render 'layouts/search'
  / br
  / a href="#" class="trigger-geolocate"
  /   h3 Find schools near my current location

.row
  .col-xs-8
    h1
    - if @schools.any?
      h2= "Nearby (#{@request_location || "unknown location"}) schools:"
      ul
        - @schools.each do |school|
          li
            = render :partial => 'school', :object => school
    - else
      h2
        | No schools found near #{@request_city}

app/views/home/search.html.slim
.row
  .main-search
    = render 'layouts/search'


.row
  .col-xs-8
    h1
    - if @schools.any?
      h2 Search Results
      ul
        - @schools.each do |school|
          li
            = render :partial => 'school', :object => school
    - else
      h2= "No schools found matching #{params[:query]}"

app/views/home/show.html.slim
.row
	.span8
		h1= school.name

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      / button.navbar-toggle.collapsed type="button" data-togle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
      /   span class="sr-only" Toggle navigation
      /   span class="icon-bar"
      /   span class="icon-bar"
      /   span class="icon-bar"
      = link_to 'NCES School Data Search', root_url, class: 'navbar-brand'
    div id="navbar" class="navbar-collapse collapse"
      ul class="nav navbar-nav"
        / li class="active"
        /   a href="#" Home
        / li
        /   a href="#about" About
        / li
        /   a href="#contact"
        / li class="dropdown"
        /   a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"="Dropdown <span class=\"caret\"></span>".html_safe
        /   ul class="dropdown-menu"
        /     li
        /       a href="#" Action
        /     li 
        /       a href="#">Another action
        /     li
        /       a href="#" Something else here
        /     li role="separator" class="divider"
        /     li class="dropdown-header" Nav header
        /     li
        /       a href="#" Separated link
        /     li
        /       a href="#" One more separated link
      ul class="nav navbar-nav navbar-right"
        / li
        /   a href="../navbar/" Default
        / li
        /   a href="../navbar-static-top/" Static top
        / li class="active"
        /   a href="./"= "Fixed top <span class=\"sr-only\">(current".html_safe


/ h2= link_to "NCES School Data Search", root_path, :class => 'brand'

app/views/layouts/_search.html.slim
div.search
  h1
    | Search for a school

  form#main_search action="/search" method="GET" class="form-search"
    .search-box
      input type="text" class="input-medium search-query input-xlarge" placeholder="Enter school name or zip code" name="query" value="#{params[:query] || params[:zip]}"
      
      a.submit_icon href="#"
        span.glyphicon.glyphicon-search aria-hidden="false"

      / hidden
      button type="submit" class="btn btn-primary sr-only" style="visibility: hidden" Search

javascript:
  $(function() {
    $('.submit_icon').click(function () {
      $('#main_search').submit();
      return false;
    });
  });

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      title= content_for?(:title) ? yield(:title) : "Nces Lookup"
      meta content=(content_for?(:description) ? yield(:description) : "Nces Lookup") name="description" 
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Scada:400,700|Cardo:400,700"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  body class=("#{controller_name} #{action_name}") 
    = render 'layouts/navigation'
    #main role="main" 
      .container-fluid
        .row
          .col-xs-6.col-xs-offset-3
            = render 'layouts/messages'
            = yield
        footer
          span.tagline Frolicking through NCES data.
          span.tagline.pull-left
            a href="http://github.com/amoose/JauNCES" target="_blank" Fork me on GitHub!
          br clear="both"
      /! ! end of .container-fluid
    /! ! end of #main

app/views/schools/show.html.slim
.row.search-results
	.span8
		h1= @school.name

		table.table
			tr
				th
					| NCES School ID
				th
					| Low Grade
				th
					| High Grade
				th
					| District
				th
					| Address
				th
					| Phone
				th
					| Students
				th
					| Teachers
			tr
				td= @school.nces_school_id
				td= @school.low_grade
				td= @school.high_grade
				td= @school.district
				td= @school.address
				td= @school.phone
				td= @school.students
				td= @school.teachers

	.span4
		= render "layouts/search"